services:
  - type: web
    name: u1st-gadget-shop
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: sh -c "python manage.py migrate --noinput && python manage.py seed_gadgets && gunicorn u1stgadget.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: u1stgadget.settings
      - key: DJANGO_DEBUG
        value: "true"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"